# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- powershell: |
        #Invoke-WebRequest -Uri https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-win64.tar.gz -OutFile $(Agent.BuildDirectory)/s/codeql-bundle-win64.tar.gz
        #tar -xvzf $(Agent.BuildDirectory)/s/codeql-bundle-win64.tar.gz
        echo current working directory
        pwd
        echo list directory
        ls
        #./codeql/codeql resolve qlpacks
        echo Agent build directory $(Agent.BuildDirectory)
        echo Agent HomeDirectory directory $(Agent.HomeDirectory)
  displayName: 'Download Codeql CLI package'
  
- task: CmdLine@1
  displayName: CodeQL Initialization
  inputs:
    script: "%CodeQLRunner%\\codeql-runner-win.exe init --repository chandrasekarMariappan/sa --languages csharp --github-url https://github.com --github-auth $(CICD_TOKEN)"



