# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  #vmImage: 'Windows-latest'
  name: PECOE-self-hosted

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- powershell: |
    Invoke-WebRequest -Uri https://github.com/github/codeql-action/releases/latest/download/codeql-bundle-win64.tar.gz -OutFile $(System.DefaultWorkingDirectory)/codeql-bundle-win64.tar.gz
    tar -xvzf $(System.DefaultWorkingDirectory)/codeql-bundle-win64.tar.gz
  displayName: 'Download Codeql CLI package'

- task: CmdLine@2
  displayName: CodeQL Initialization
  inputs:
    script: |
      mkdir $(System.DefaultWorkingDirectory)\codeql\codeql-dbs
      echo "ls codeql directory"
      ls $(System.DefaultWorkingDirectory)/codeql
      $(System.DefaultWorkingDirectory)\codeql\codeql database init --language csharp --trace-process-name Agent.Worker.exe --source-root . --begin-tracing $(System.DefaultWorkingDirectory)/codeql/codeql-dbs/sec-poc-demo-dotnet-repo
      echo "json directory path"
      ls $(System.DefaultWorkingDirectory)/codeql/codeql-dbs/sec-poc-demo-dotnet-repo/temp/tracingEnvironment 

- task: PowerShell@2
  displayName: Set CodeQL Environment Variables
  inputs:
   targetType: inline
   script: >
          $json = Get-Content $(System.DefaultWorkingDirectory)/codeql/codeql-dbs/sec-poc-demo-dotnet-repo/temp/tracingEnvironment/start-tracing.json | ConvertFrom-Json
          $json.PSObject.Properties | ForEach-Object {
              $template = "##vso[task.setvariable variable="
              $template += $_.Name
              $template += "]"
              $template += $_.Value
              echo "$template"
          }

# Execute a clean build using the VSBuild task.
- task: VSBuild@1
  inputs:
      solution: '**/*.sln'
      msbuildArgs: '/p:OutDir=$(Build.ArtifactStagingDirectory) /p:UseSharedCompilation=false'
      platform: Any CPU
      configuration: Release
      clean: True
  displayName: Visual Studio Build