# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: |
    wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20221202/codeql-bundle-win64.tar.gz
    chmod +x codeql-bundle-win64.tar.gz
  displayName: 'Get latest CodeQL package. Install on Agent.'